name: CI

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

jobs:
  build:
    # Prevent running workflow twice on a PR from a non-fork
    # We could use Skip Duplicate Actions, but this is shorter
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Restore
        run: |
          dotnet restore Il2CppInterop.Common/Il2CppInterop.Common.csproj
          dotnet restore Il2CppInterop.Runtime/Il2CppInterop.Runtime.csproj

      - name: Build
        run: |
          dotnet build Il2CppInterop.Common/Il2CppInterop.Common.csproj --configuration Release --no-restore /p:ContinuousIntegrationBuild=true /p:GeneratePackageOnBuild=false
          dotnet build Il2CppInterop.Runtime/Il2CppInterop.Runtime.csproj --configuration Release --no-restore /p:ContinuousIntegrationBuild=true /p:GeneratePackageOnBuild=false

      - name: Pack
        run: |
          dotnet pack Il2CppInterop.Common/Il2CppInterop.Common.csproj --configuration Release --no-build --output artifacts/package /p:ContinuousIntegrationBuild=true
          dotnet pack Il2CppInterop.Runtime/Il2CppInterop.Runtime.csproj --configuration Release --no-build --output artifacts/package /p:ContinuousIntegrationBuild=true

      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: snwcreations-il2cppinterop-packages
          path: artifacts/package/*.nupkg
          if-no-files-found: error

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Download packages
        uses: actions/download-artifact@v4
        with:
          name: snwcreations-il2cppinterop-packages
          path: artifacts/package

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ contains(github.ref_name, '-') }}
          generate_release_notes: true
          files: artifacts/package/*.nupkg
